### ISSUE TITLE
not supported edge cases

### ISSUE THREAD

**Issue by armano2** [d3/d3-delaunay#54] opened 2019-01-10 16:36 UTC
i found few edge cases,

when points provided to Delaunay are on one line (x or y axis) delaunay is not able to produce correct result, and it throwing error with 

```
Error: No Delaunay triangulation exists for this input.
```

that's a case even no matter how many points there in single line.
this was not a case with `d3-voronoi`

points
```
[20,0,107.24319391634981,0,188.8577946768061,0,275.9837262357414,0,360.4126235741445,0,447.6558174904943,0,532.0847148288974,0,619.3279087452472,0,706.5711026615969,0,791,0]
```

**Comment by mbostock** [comment] 2019-01-10 17:01
Duplicate of #20.

**Closed by mbostock** 2019-01-10 17:01 UTC
