### ISSUE TITLE
No Delaunay triangulation for n = 3 array

### ISSUE THREAD

**Issue by emeeks** [d3/d3-delaunay#48] opened 2018-09-10 15:38 UTC
`Delaunay.from([[0,171],[0,62],[0,15]])` 

complains with:

```
index.js:91 Uncaught Error: No Delaunay triangulation exists for this input.
    at new Delaunator (index.js:91)
    at new Delaunay (delaunay.js:18)
```

**Comment by emeeks** [comment] 2018-09-10 15:40
Oh is it because the straight-line through point two means this is effectively an n=2 array?

**Comment by mbostock** [comment] 2018-09-10 15:50
Duplicate of #20.

**Closed by mbostock** 2018-09-10 15:50 UTC
