### ISSUE TITLE
Odd failure

### ISSUE THREAD

**Issue by madcowfpb** [d3/d3-delaunay#141] opened 2023-03-25 04:44 UTC
I haven't tried to exactly isolate the bug yet, but the attached exhibits a failure case. The voronoi library at https://github.com/Dozed12/p5.voronoi seems to handle this set of points correctly. It looks like the circumcenters are correctly computed.

[vfail2.txt](https://github.com/d3/d3-delaunay/files/11068026/vfail2.txt)

**Comment by mbostock** [comment] 2023-03-25 05:15
Here is a notebook to reproduce: https://observablehq.com/d/7624520d45e4b44f (In the future, if you’d be willing to share these reproductions as an Observable notebook, it would save us some time. Thank you!)

It renders fine when scaled and translated, as here with Plot:

![untitled (32)](https://user-images.githubusercontent.com/230541/227697726-d4f27448-f454-4236-9767-0097ae3a36fb.png)

```js
Plot.marks(Plot.voronoi(points), Plot.delaunayMesh(points)).plot()
```

But it looks like the there are some problems computing the Voronoi cell edges for points on the Delaunay hull.

![image](https://user-images.githubusercontent.com/230541/227697779-0ab6ff04-ee2f-43af-98eb-4bd4a9247ff1.png)

**Comment by Fil** [comment] 2023-03-25 07:41
Not that it helps much to understand why the bug happens, but this test case is correct under d3-delaunay@4.

**Comment by Fil** [comment] 2023-03-25 09:08
In the collinear case (a "flat triangle" on the hull) https://github.com/d3/d3-delaunay/blob/48d091fb7da5c354d7a148b944524ca86c68ecb4/src/voronoi.js#L41, we compute _a_ to cast a long ray (1e9) towards the exterior in order to compute the circumcenter as the "point at infinity".

In this case a is sometimes 0, or going in the wrong direction, because the reference point _r_ (point 36, marked as a green circle) happens to be exactly on the hull, and collinear with the (flat) triangle whose circumcenter we're trying to compute.

<img width="510" alt="Capture d’écran 2023-03-25 à 10 01 57" src="https://user-images.githubusercontent.com/7001/227707825-15f40a3e-5f2e-41ba-a8ef-3c8fdc5b2e37.png">

So, any segment on the collinear part of the hull has a 1/2 chance to be projected in the wrong direction. This results in the weird polygonCell 180 (also in green).

A quick and dirty patch:
```diff
-        const r = triangles[0] * 2;
-        a *= Math.sign((points[r] - x1) * ey - (points[r + 1] - y1) * ex);
+        let i=0;
+        while (i < triangles.length && Math.abs(a) < 1e-3) {
+          const r = triangles[i++] * 2;
+          a =  ((points[r] - x1) * ey - (points[r + 1] - y1) * ex);
+        }
+        a = Math.sign(a) * 1e9;
```

There might be a better approach though, using the fact that the points are enumerated clockwise? Needs a bit more thought.

**Comment by Fil** [comment] 2023-03-25 14:31
#142 fixes it, thanks for the test case!

**Closed** 2023-04-01 02:38 UTC
Labels: bug
